### ISSUE TITLE
toggle() not turning switch from on to off

### ISSUE THREAD

**Issue by klohner** [GaryMilne/Hubitat-Tasmota#9]
The toggle command wouldn't toggle my switch to "off" if it was already "on". 

I was able to trace the issue to this line:

https://github.com/GaryMilne/Hubitat-Tasmota/blob/2980cd2a7d86f723dbcb2e1f94cc6c261ad62b25/Single_Relay_Switch_Plug.groovy#L1568

Changing "switch1" to "switch" resolved the issue.

`    if (device.currentValue("switch") == "on") off()`

**Comment by GaryMilne** [comment]
Thank you.
